redis:
  image: "redis:4-alpine"
node:
  image: "emotobooth:4"
  environment:
    - NODE_ENV=production
  ports:
    - "8080:8080"
    - "9229:9229"
  links:
    - redis
  volumes:
    - ./data/in:/app/data/in